### PR TITLE
Add name property to redirect destination

### PR DESCRIPTION
**Pull request by ivar-lazzaro**
APIC will use it to order the redirection IPs

### CODE REVIEW

**Comment by amittbose** [comment]
Change looks good. However there is a Travis failure, possibly unrelated to this change.

**Comment by tbachman** [comment]
This may be a failure due to a change in oslo.config. The last passing version had 5.2.0, while this one uses 6.0.0. Looks like they may have removed the MultiConfigParser

**Comment by ivar-lazzaro** [comment]
we can merge this if you guys approve of the change

**Comment by amittbose** [comment]
Please rebase

**Comment by ivar-lazzaro** [comment]
done

**Pull request merged**
