### PR TITLE
Fix for scaling issue of static paths

### PR DESCRIPTION
**Pull request by timeu**
This is a fix for the scaling issue on in #309.

A new testcase `test_static_path_scale ` was added to test the scaling of static paths. 
In the testcase we add 199 static paths and then in a second step add one new static path, remove one existing and update another one. 

The fix for this issue is to update the static paths in place instead of re-creating them every time even when only one new static path is added.

Here are some numbers:

Runtime of the `test_static_path_scale` test:  

- Fixed version:      2.2s
- Original version: 10.9s 

This is also visible in the number of SELECT statements on the aim_endpoint_groups table:
- Fixed version:         7 
- Original version: 206

### CODE REVIEW

**Review by tbachman — CHANGES_REQUESTED** [review]
This looks great, and a huge thanks for the PR! Only two minor change requests here:
1) Make sure that the line lengths don't exceed 80 characters
2) squash the commits into a single one

Otherwise, this looks good to me , and thanks!

**Comment by timeu** [comment]
@tbachman thx! will do later today

**Comment by timeu** [comment]
@tbachman  squashed commits and made pep8 pass cleanly.

**Comment by tbachman** [comment]
Thanks for the patch!

**Pull request merged**
