### PR TITLE
Add GARP configuration for gen1 hardware

### PR DESCRIPTION
**Pull request by tbachman**
First generation switches are unable to use GARPs for EP movement detection in hardware when the EP "move" is on the same port..As a result, additional configuraiton is needed in the BD to punt all GARPs to the switch CPU for processing. This patch adds an AIM parameter to control how this behavior is configured in the fabric, with the default configuration to disable it (i.e. default is to not support use of GARPs for EP movement detection on gen1 hardware).

### CODE REVIEW

**Review by sayalinaval — APPROVED** [review]

**Comment by tbachman** [comment]
Hold off on merging this - I want to create a data migration DB migration, which changes the values of existing BDSs.

**Comment by tbachman** [comment]
Just updated the test with the data migration (and UT that tests it). Ready for reviews.

**Review by christides11 — APPROVED** [review]

**Review by sayalinaval — APPROVED** [review]

**Comment by tbachman** [comment]
I just realized - the data migration doesn't consider the configuration variable. Let me fix that and re-spin.

**Comment by tbachman** [comment]
Just pushed latest changes.

**Review by sbagalur — APPROVED** [review]

**Pull request merged**
